#!/bin/sh /etc/rc.common
# procd-managed init for ubus-wsd. Triggers a restart on /etc/config/ubus-ws
# changes, depends on rpcd so session.access is available at startup.

START=99
USE_PROCD=1

PROG=/usr/sbin/ubus-wsd

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param netdev wan         # restart if WAN comes up
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "ubus-ws"
}

reload_service() {
	stop
	start
}
